# 02 - Limpeza dos Dados

Aplicação das correções identificadas na EDA:
remoção de nulos, duplicatas, cancelamentos,
valores inválidos e correção de tipagem.

In [81]:
import pandas as pd
import numpy as np

In [82]:
df = pd.read_csv('../data/raw/online_retail_II.csv')

In [83]:
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [84]:
df_original_shape = df.shape

In [85]:
print(f"Shape inicial: {df.shape}")

Shape inicial: (1067371, 8)

### Limpeza Inicial

In [86]:
df.drop_duplicates(inplace=True)

In [87]:
df.shape

(1033036, 8)

34335 linhas duplicadas removidas

In [88]:
df.duplicated().sum()

np.int64(0)

In [89]:
df.shape

(1033036, 8)

In [90]:
df['Invoice'].str.startswith("C").sum()
# me trás todo os registros de faturas canceladas

np.int64(19104)

In [91]:
df = df[~df['Invoice'].str.startswith("C")]
# Remove todas as faturas canceladas

In [92]:
df['Invoice'].str.startswith("C").sum()

np.int64(0)

In [93]:
df.shape

(1013932, 8)

Remoção de dados da coluna "Quantity" inválidos

In [94]:
quantity_invalidos = df['Quantity'] < 0

In [95]:
quantity_invalidos.sum()

np.int64(3393)

In [96]:
print(df.loc[quantity_invalidos, ['Invoice', 'Quantity']].head())

     Invoice  Quantity
263   489464       -96
283   489463      -240
284   489467      -192
470   489521       -50
3114  489655       -44

In [97]:
df[df['Quantity'] < 0]['Customer ID'].isna().sum()

np.int64(3393)

In [98]:
(df['Quantity'] < 0).sum()

np.int64(3393)

In [99]:
df = df[~(df['Quantity'] < 0)]

In [100]:
(df['Quantity'] < 0).sum()
# Verificação

np.int64(0)

Remoção de dados da coluna "Price" inválidos

In [101]:
df.shape

(1010539, 8)

In [102]:
price_invalidos = df['Price'] < 0
price_invalidos.sum()

np.int64(5)

In [103]:
df[df['Price'] < 0]['Customer ID'].isna().sum()

np.int64(5)

In [104]:
df[df['Price'] < 0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom
825444,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
825445,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [105]:
df = df[~(df['Price'] < 0)]

In [106]:
df.shape

(1010534, 8)

Correção dos tipos das colunas

In [107]:
df.dtypes

Invoice         object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
Price          float64
Customer ID    float64
Country         object
dtype: object

In [108]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [109]:
df['Customer ID'].isna().sum()

np.int64(231039)

In [110]:
df['Customer ID'].isna().mean() * 100

np.float64(22.863060520477294)

##### 22,86% da base de dados de Customer ID são valores nulos

In [111]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      1642
Quantity            0
InvoiceDate         0
Price               0
Customer ID    231039
Country             0
dtype: int64

In [112]:
df[df['Description'].isna()]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
6378,489882,35751C,NaN,12,2009-12-02 16:22:00,0.0,NaN,United Kingdom
6555,489898,79323G,NaN,954,2009-12-03 09:40:00,0.0,NaN,United Kingdom
6581,489903,21166,NaN,48,2009-12-03 09:57:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
1059173,581103,22689,NaN,4,2011-12-07 11:58:00,0.0,NaN,United Kingdom
1060787,581203,23406,NaN,15,2011-12-07 18:31:00,0.0,NaN,United Kingdom
1060793,581209,21620,NaN,6,2011-12-07 18:35:00,0.0,NaN,United Kingdom
1062442,581234,72817,NaN,27,2011-12-08 10:33:00,0.0,NaN,United Kingdom
1064015,581408,85175,NaN,20,2011-12-08 14:06:00,0.0,NaN,United Kingdom

In [113]:
# Remoção dos dados nulos de Customer ID
df = df.dropna(subset=['Customer ID'])

In [114]:
df['Customer ID'] = df['Customer ID'].astype(int)

In [118]:
df.dtypes

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID             int64
Country                object
dtype: object

In [116]:
print(f"Shape inicial: {df_original_shape}")
print(f"Shape final após limpeza: {df.shape}")

Shape inicial: (1067371, 8)
Shape final após limpeza: (779495, 8)

In [117]:
df.to_csv('../data/processed/online_retail_cleaned.csv', index=False)
print("O Dataset limpo foi salvo com sucesso")

O Dataset limpo foi salvo com sucesso

## Limpeza dos Dados

Foram removidos registros duplicados, transações canceladas, ajustes administrativos, valores inválidos e registros sem identificação de cliente. Também foram realizados ajustes nos tipos de dados das colunas.

*Shape inicial:* (1.067.371, 8)  
*Shape final:* (779.495, 8)

Ao final da etapa de limpeza, permaneceram apenas registros válidos para a análise RFM.